export const ME_IMG = '/images/me.jpg'
export const RPIO_IMG = '/images/rpio-hero.png'
export const ALOY_IMG = '/images/aloy-dashboard.png'
export const SAAS_IMG = '/images/saas.png'
export const LEVELUP_IMG = '/images/levelup.png'
